---
name: Build Java project
description: |-
  This action build a Java Maven project

inputs:
  run-tests:
    description: |-
      Run defined tests
    default: 'true'

runs:
  using: "composite"
  steps:
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      id: maven-build
      shell: bash
      run: mvn -B clean package

    - name: Run tests
      id: maven-test
      if: ${{ inputs.run-tests == 'true' }}
      shell: bash
      run: mvn test
